# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc8f2bed8a6f41a4452cb49425db0fc11b5cc15a24b7c38a1790112bc74a24d60998d4026f52e5896763b889d490a22389008659e44fa5bf83136b79aed032f

test:
  secret_key_base: dd778669b3332d5af2bbedac0247078250271a03a8b0fd9d6838fc3f77d169e407d333a4db8a132e6b868a5ded06c2be8ccad53c2730cd880649a13cb9f3ac25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
